### PR TITLE
Add AngelChest compatibility, fixes #1

### LINKED ISSUE #1: Problems with AngelChest: [pdd] lore
Hi, I am the author of AngelChest. Whenever a player dies and their items get put into the AngelChest, their items are tagged with a "[pdd]" lore.
If you would change the PlayerDeathEvent priority to MONITOR, this should be fixed, so that both plugins are compatible.

### PR DESCRIPTION
**Pull request by mfnalex**
changed EventPriority to avoid items collected by the AngelChest plugin being tagged with the [pdd] lore, fixes #1

### CODE REVIEW

**Comment by Xezard** [comment]
Dismissed PR because using EventPriority.MONITOR is not recommended. Changed to EventPriority.HIGHEST.

**Comment by mfnalex** [comment]
Highest will not work. You should use MONITOR since you don't really change the itemstack itself

**Comment by Xezard** [comment]
> Highest will not work. You should use MONITOR since you don't really change the itemstack itself

But I change the lore of the itemstack until the ItemSpawnEvent, where this lore line is removed and the required amount of time is added.  EventPriority.MONITOR is not intended for this kind of action and may cause conflicts with other plugins.

**Comment by mfnalex** [comment]
You change the itemstack, but not the event. Well I don't care, but it will be a 50/50 chance if this will work with AngelChest as AngelChest also listens on HIGHEST. You don't cancel the event or alter it in any way so there is no problem using MONITOR.

**Pull request closed without merging**
